//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DataBasePath {
            get {
                return ((string)(this["DataBasePath"]));
            }
            set {
                this["DataBasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmItemSelectLocX {
            get {
                return ((int)(this["FrmItemSelectLocX"]));
            }
            set {
                this["FrmItemSelectLocX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmItemSelectLocY {
            get {
                return ((int)(this["FrmItemSelectLocY"]));
            }
            set {
                this["FrmItemSelectLocY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmItemSelectSizeW {
            get {
                return ((int)(this["FrmItemSelectSizeW"]));
            }
            set {
                this["FrmItemSelectSizeW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmItemSelectSizeH {
            get {
                return ((int)(this["FrmItemSelectSizeH"]));
            }
            set {
                this["FrmItemSelectSizeH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmEditCostLocX {
            get {
                return ((int)(this["FrmEditCostLocX"]));
            }
            set {
                this["FrmEditCostLocX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmEditCostLocY {
            get {
                return ((int)(this["FrmEditCostLocY"]));
            }
            set {
                this["FrmEditCostLocY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmEditCostSizeW {
            get {
                return ((int)(this["FrmEditCostSizeW"]));
            }
            set {
                this["FrmEditCostSizeW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmEditCostSizeH {
            get {
                return ((int)(this["FrmEditCostSizeH"]));
            }
            set {
                this["FrmEditCostSizeH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMainLocX {
            get {
                return ((int)(this["FrmMainLocX"]));
            }
            set {
                this["FrmMainLocX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMainLocY {
            get {
                return ((int)(this["FrmMainLocY"]));
            }
            set {
                this["FrmMainLocY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMainSizeW {
            get {
                return ((int)(this["FrmMainSizeW"]));
            }
            set {
                this["FrmMainSizeW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FrmMainSizeH {
            get {
                return ((int)(this["FrmMainSizeH"]));
            }
            set {
                this["FrmMainSizeH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public float ItemSelectFontSize {
            get {
                return ((float)(this["ItemSelectFontSize"]));
            }
            set {
                this["ItemSelectFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public float ProductListFontSize {
            get {
                return ((float)(this["ProductListFontSize"]));
            }
            set {
                this["ProductListFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int ItemSelectColChkW {
            get {
                return ((int)(this["ItemSelectColChkW"]));
            }
            set {
                this["ItemSelectColChkW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ItemSelectColKindW {
            get {
                return ((int)(this["ItemSelectColKindW"]));
            }
            set {
                this["ItemSelectColKindW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ItemSelectColNameW {
            get {
                return ((int)(this["ItemSelectColNameW"]));
            }
            set {
                this["ItemSelectColNameW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int ProductListColChkW {
            get {
                return ((int)(this["ProductListColChkW"]));
            }
            set {
                this["ProductListColChkW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ProductListColKindW {
            get {
                return ((int)(this["ProductListColKindW"]));
            }
            set {
                this["ProductListColKindW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ProductListColNameW {
            get {
                return ((int)(this["ProductListColNameW"]));
            }
            set {
                this["ProductListColNameW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ProductListColNumW {
            get {
                return ((int)(this["ProductListColNumW"]));
            }
            set {
                this["ProductListColNumW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ProductListColCostRateW {
            get {
                return ((int)(this["ProductListColCostRateW"]));
            }
            set {
                this["ProductListColCostRateW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ProductListColMaterialW {
            get {
                return ((int)(this["ProductListColMaterialW"]));
            }
            set {
                this["ProductListColMaterialW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ProductListColWorkerlW {
            get {
                return ((int)(this["ProductListColWorkerlW"]));
            }
            set {
                this["ProductListColWorkerlW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ProductListColPackageW {
            get {
                return ((int)(this["ProductListColPackageW"]));
            }
            set {
                this["ProductListColPackageW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ProductListColPriceW {
            get {
                return ((int)(this["ProductListColPriceW"]));
            }
            set {
                this["ProductListColPriceW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public int ProductListColProfitW {
            get {
                return ((int)(this["ProductListColProfitW"]));
            }
            set {
                this["ProductListColProfitW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DispIDtoList {
            get {
                return ((bool)(this["DispIDtoList"]));
            }
            set {
                this["DispIDtoList"] = value;
            }
        }
    }
}
